name: NPM CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Corepack for pnpm
        run: corepack enable

      - name: Setup Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Bulid Artifacts
        run: pnpm build

      # - name: Run Tests
      #   run: pnpm test

      - name: Lint Code
        run: pnpm lint || echo "Linting failed, but continuing"

      # - name: Format Code
      #   run: pnpm format

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: 'chore(release): update version'
          commit: 'chore(release): update version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
